[[items]]
date = "2024.12"
name = "49th ACM-ICPC Asia East Continent Final (EC-Final)"
prize = "Bronze Medal"
role = "Team Member"

[[items]]
date = "2024.11"
name = "19th \"Challenge Cup\": 2024 'Open Call for Solutions' Special Program"
prize = "Second Prize"
role = "Team Leader"

[[items]]
date = "2024.09"
name = "2024 Weihai Collegiate Programming Contest"
prize = "Gold Medal"
role = "Team Member"

[[items]]
date = "2024.04"
name = "Huawei CodeCraft Contest 2024"
prize = "Second Prize"
role = "9th in Preliminary Round"

[[items]]
date = "2023.12"
name = "48th ACM-ICPC Asia Regional Contest, Hangzhou"
prize = "Silver Medal"
role = "Team Member"

[[items]]
date = "2023.11"
name = "48th ACM-ICPC Asia Regional Contest, Nanjing"
prize = "Bronze Medal"
role = "Team Member"

[[items]]
date = "2023.10"
name = "2023 CCF Collegiate Computer Systems & Programming Contest"
prize = "Bronze Medal"
role = "Team Member"
