[[news]]
date = "2026.04"
content = "🎉 Two papers (Vid-LLMs Editing & Financial alpha mining Framework) have been accepted by **Main Conference of 🇺🇸 ACL 2026**!"

[[news]]
date = "2026.03"
content = "🎉 I got the Phd offer from 🇭🇰 **The Chinese University of Hong Kong (CUHK)**!"

[[news]]
date = "2025.12"
content = "🏆 Awarded the **Zeshi Virtue and Talent Scholarship**, one of the prestigious scholarships at Harbin Institute of Technology, Weihai!"

[[news]]
date = "2025.10"
content = "🏆 Honored to be awarded the **National Scholarship 2024-2025** (Top 0.4% Nationwide)!"

[[news]]
date = "2025.08"
content = "🎉 Our paper on deductive and inductive reasoning has been accepted by **Findings of 🇨🇳 EMNLP 2025**!"

[[news]]
date = "2025.05"
content = "🎉 Our paper [ScEdit](https://aclanthology.org/2025.findings-acl.104/) has been accepted by **Findings of 🇦🇹 ACL 2025**! My first first-author paper!"

[[news]]
date = "2025.05"
content = "🎉 Shared task paper [LLMSR@XLLM25](https://aclanthology.org/2025.xllm-1.30/) accepted by **ACL 2025 XLLM Workshop**."

[[news]]
date = "2024.12"
content = "🥉 Our team won a **Bronze Medal** in **ICPC EC-Final**!"

[[news]]
date = "2024.11"
content = "🏅 Our project was awarded **Second Prize** in the **\"Challenge Cup\"**."

[[news]]
date = "2024.07"
content = "🎉 Our paper on debiasing MLLMs via model editing has been accepted by ** 🇦🇺 ACM MM 2024**!"
